# Generated by Django 4.2.1 on 2023-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ceramic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceramic_name', models.CharField(max_length=20)),
                ('ceramic_img', models.ImageField(upload_to='products')),
            ],
        ),
    ]
