# Generated by Django 4.2.1 on 2023-08-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ceramic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ceramic',
            new_name='ceramics',
        ),
    ]
