# Generated by Django 4.2.1 on 2023-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ceramics_ceramic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='planters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planter_name', models.CharField(max_length=20)),
                ('planter_id', models.IntegerField(null=True)),
            ],
        ),
    ]
