# Generated by Django 4.2.1 on 2023-08-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_candles_planters_planter_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_id', models.IntegerField(null=True)),
                ('card_img', models.ImageField(null=True, upload_to='products')),
            ],
        ),
    ]
