# Generated by Django 4.2.1 on 2023-08-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='candle_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ceramics',
            name='ceramic_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='planters',
            name='planter_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
