# Generated by Django 4.2.1 on 2023-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_candles_candle_id_alter_cards_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='candle_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ceramics',
            name='ceramic_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='planters',
            name='planter_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
